version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LOG_RETENTION_MINUTES=30
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - /home/kafka/broker-1/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9093
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LOG_RETENTION_MINUTES=30
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9093:9093"
    volumes:
      - /home/kafka/broker-2/logs:/opt/bitnami/kafka/logs
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9093
      # Uncomment the following lines to enable basic authentication
      # - KAFKA_UI_BASIC_AUTH_USER=admin
      # - KAFKA_UI_BASIC_AUTH_PASSWORD=admin
    ports:
      - "8090:8080"
    depends_on:
      - kafka-1
      - kafka-2
    networks:
      - kafka-net
